env:
  browser: true
  commonjs: true
  es6: true
  node: true

plugins:
  - prettier

extends: plugin:prettier/recommended

parser: babel-eslint
parserOptions:
  ecmaVersion: 2018
  sourceType: module
