endOfLine: lf
tabWidth: 4
useTabs: false
singleQuote: true
bracketSpacing: true
semi: false
arrowParens: always
plugins:
  - 'prettier-plugin-twig-melody'
twigMelodyPlugins:
  - 'node_modules/prettier-plugin-twig-enhancements'
twigPrintWidth: 120
twigFollowOfficialCodingStandards: false
overrides:
  - files:
      - '*.js'
    options:
      printWidth: 80
  - files:
      - '*.json'
    options:
      useTabs: true
  # - files:
  #     - 'Makefile'
  #   options:
  #     useTabs: true
  - files:
      - '*.yml'
      - '*.yaml'
      - '*.md'
      - 'package.json'
    options:
      tabWidth: 2
      useTabs: false
  - files:
      - '*.njk'
    options:
      parser: melody
      printWidth: 120
      htmlWhitespaceSensitivity: ignore
