endOfLine: lf
tabWidth: 4
useTabs: false
singleQuote: true
bracketSpacing: true
semi: false
arrowParens: always

overrides:
  - files:
      - '*.js'
    options:
      printWidth: 80
  - files:
      - '*.json'
    options:
      useTabs: true
  # - files:
  #     - 'Makefile'
  #   options:
  #     useTabs: true
  - files:
      - '*.yml'
      - '*.yaml'
      - 'package.json'
    options:
      tabWidth: 2
      useTabs: false
  - files:
      - '*.njk'
    options:
      parser: html
      printWidth: 120
      htmlWhitespaceSensitivity: ignore
